name: Cypress Tests and Allure Report

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npm run test:cypress

    - name: Generate Allure report
      run: allure generate

    - name: Publish Allure report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report