name: Cypress Tests with Allure Report

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Run Cypress Tests
      run: npm run cy:run:login || true
    
    - name: Generate Allure Report
      run: npm run allure:report

    - name: Update Allure History
      run: npm run allure:history2

    - name: Publish Allure Report to GitHub Pages
      uses: simple-elf/allure-report-action@v1
      with:
        allure_results: allure-results
        allure_report: allure-report
        gh_pages: true

    - name: Commit and Push Allure Report History
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add allure-history
        git commit -m "Update Allure Report History"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}